version: "3"

services:
  app:
    image: georgetourtsin/ubuntu-nginx:latest
    container_name: "${PROJECT_NAME}_app"
    volumes:
      - ./:/var/www/html
      - ./php-settings/php.ini.tpl:/etc/confd/templates/php.ini.tpl
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./nginx-settings/default.conf.tpl:/etc/confd/templates/default.conf.tpl
    environment: 
      NGINX_HOST: $PROJECT_URL
      NGINX_PORT: 80
      NGINX_ROOT: /var/www/html/public_html
      VIRTUAL_HOST: $PROJECT_URL
    links:
      - db:db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_NAME
      MYSQL_PASSWORD: $DB_USER
    container_name: "${PROJECT_NAME}_db"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: "${PROJECT_NAME}_pma"
    links:
      - db:db
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      VIRTUAL_HOST: pma.${PROJECT_URL}


networks:
  default:
    external:
      name: nginx-proxy